singlish_l = [
        ("ah beng","teenage male hooligan"),
        ("ah seng","teenage hooligan"),
        ("ah kar", "clumsy"),
        ("ah chew","clumsy"),
        ("ah gua","transvetite sissy"),
        ("ah lian","teengage female hooligan"),
        ("ah long","loan shark"),
        ("ah soh","auntie"),
        ("ai wan","wasted wrong"),
        ("ak kah ji","very good friendship"),
        ("ai","want"),
        ("ai bia jia oei ya","strive to win"),
        ("ai pee ai chee","want something good and cheap"),
        ("aiyah","oh dear"),
        ("aiyoh","oh dear"),
        ("ai zai","calm down"),
        ("am bai","police inspector"),
        ("an zua","how and why"),
        ("ang moh","Caucasian"),
        ("ang moh chu","bungalow"),
        
        ("ba wu","pungent smell"),
        ("bin chao chao","grumpy look"),
        ("boh beh zao","exceptional, no competition"),
        ("boh bian","no choice"),
        ("boh chup","don't bother"),
        ("boh dai ji","nothing is wrong"),
        ("boh dua bo sio","disrespectful"),
        ("boh dui pi","something's not right"),
        ("boh eng","not free"),
        ("boh her hay ma hou","accepting for the lesser"),
        ("boh hua","not worth it"),
        ("boh hue","ignore"),
        ("boh jio","not inviting"),
        ("boh li you","unreasonable"),
        ("boh liao","boring"),
        ("boh li you","unreasonable"),
        ("boh liao","boring"),
        ("boh lui","broke"),
        ("boh seh","without style"),
        ("buay gam","can't match"),
        ("buay gum wan","unwillingly"),
        ("buay lin chu","incur heavy losses"),
        ("buay zi dong","inconsiderate"),
        ("buay","cannot"),
        ("cha siao","ridicule"),
        ("ji siao","ridicule"),
        ("chi kat","wasted or wronged"),
        ("cham siong","discuss"),
        ("cham","diasastrous"),
        ("chao kar","loser"),
        ("chao keng","avoiding responsibility"),
        ("chao kuan","cheater"),
        ("chao lao","appears old"),
        ("chao","smelly"),
        ("chao ji kee","type of lottery"),
        ("char bo","woman"),
        ("char tow","blockhead"),
        ("cheng hu chu","HDB flats"),
        ("chey","humph"),
        ("chiam si dong","endure for time being"),
        ("chim","difficult to understand"),
        ("chin chai","anything"),
        ("chio","pretty"),
        ("chiong","party"),
        ("chor lor","rough"),
        ("chor","heavy"),
        ("chui","bad"),
        ("dai ji dua diao","big problem"),
        ("dua gao","police inspector"),
        ("dua ker hor lan","sabotage"),
        ("eh kia","short guy"),
        ("gang kor","very difficult"),
        ("ge yan","ironically amusing"),
        ("giam siap","stingy"),
        ("gin na","child"),
        ("gu niang","sissy"),
        ("gum pui","for what"),
        ("hao lian","arrogant"),
        ("hao siao","bullshit"),
        ("heng","lucky"),
        ("hiao","vain"),
        ("hiong","daring"),
        ("ho gai siao","good advice"),
        ("ho seh","great"),
        ("huat","prosperous"),
        ("jit teh bin","pulled a face"),
        ("jiak cao", "broke"),
        ("jiak gao gao","take complete advantage"),
        ("jiak hong chu", "bungalow"),
        ("jiak hong", "travel"),
        ("jiak ji gua", "corrupted official"),
        ("jiak liao bee", "useless bum"),
        ("jiak ba bo sai pang", "nothing to do"),
        ("jiak", "eat"),
        ("jio", "invite"),
        ("jiu hu", "Malaysia"),
        ("kay poh", "busybody"),
        ("ker bair", "go to jail"),
        ("ki siao", "becomes crazy"),
        ("kiam pah", "deserves a beating"),
        ("kiao kar", "nothing to do"),
        ("kiasi", "afraid of death"),
        ("kiasu", "afraid of losing out"),
        ("kio tio", "pick up"),
        ("kong kah kiao", "die"),
        ("koon", "sleep"),
        ("kum gong", "stupid"),
        ("lao jiao", "veteran"),
        ("lao kui", "ashamed"),
        ("lao sai", "diarrhea"),
        ("liak boh kiu", "clueless"),
        ("liao", "finish"),
        ("lim kopi", "drink coffee"),
        ("lim teh", "drink tea"),
        ("lok kok", "sloppy"),
        ("lor sor", "longwinded"),
        ("mai", "don't want"),
        ("mian kia", "don't be afraid"),
        ("niam", "nag"),
        ("ngiao", "stingy"),
        ("nua", "sloppy"),
        ("oei", "hello"),
        ("or ni gu", "bald-headed"),
        ("pah bung", "bad business"),
        ("pah jiao", "inaccurate"),
        ("pai kia", "young ruffian"),
        ("pai seh", "embarrassing"),
        ("pang pui", "fart"),
        ("pang seh", "to abandon"),
        ("pek chek", "exasperated"),
        ("por", "curry flavour"),
        ("puat bei", "sick"),
        ("sai kang", "unwanted tough work"),
        ("sai", "shit"),
        ("sar kar", "curry flavour"),
        ("sat sat boh chio", "stylish"),
        ("satki", "stylish"),
        ("si beh", "very"),
        ("si", "die"),
        ("siam", "get out of the way"),
        ("sian", "boring"),
        ("siao", "crazy"),
        ("simi dai ji", "what's up"),
        ("simi", "what"),
        ("sin jiao", "newbie"),
        ("sinseh", "Chinese physician"),
        ("siong", "difficult"),
        ("suaku", "old fashioned"),
        ("suan", "to mock"),
        ("suay", "unlucky"),
        ("su kah", "like"),
        ("sum por", "skinny"),
        ("swee", "good"),
        ("ter", "stupid"),
        ("ti ki", "stubborn"),
        ("tiko", "lecherous"),
        ("tio beh bio", "strike lottery"),
        ("tio", "to get"),
        ("tok cai tau", "con"),
        ("tok kong", "powerful"),
        ("towkay", "boss"),
        ("tua ki", "big headed"),
        ("walao", "oh my god"),
        ("wu ya bo", "really"),
        ("yandao", "handsome guy"),
        ("yao siew", "cruel"),
        ("zao sai", "smuggle"),
        ("zhun", "accurate"),
        ("goondu", "stupid"),
        ("ow tak", "lousy"),
        ("abang", "big bro"),
        ("agak-agak", "estimate"),
        ("aku tak tahu", "I don't know"),
        ("alamak!", "oops! oh no!"),
        ("atas", "high class"),
        ("bagus", "good"),
        ("balik kampung", "pack up go home"),
        ("belanja", "treat"),
        ("bodoh", "stupid"),
        ("boleh", "can"),
        ("busoh", "smelly"),
        ("chingay", "parade"),
        ("diam", "silence, shut up"),
        ("garang", "gung-ho"),
        ("guli", "marble"),
        ("hantu", "ghost"),
        ("hentam", "whack"),
        ("kaki", "friend"),
        ("kampung", "village"),
        ("kena", "is"),
        ("kentang", "potato"),
        ("lagi", "even"),
        ("langgar", "accident"),
        ("lelong", "auction"),
        ("macam", "just like"),
        ("makan", "eat"),
        ("mata", "police"),
        ("mati", "die"),
        ("pasar", "market"),
        ("pengsan", "faint"),
        ("ponteng", "absent"),
        ("roti", "bread"),
        ("salah", "wrong"),
        ("saman", "summon"),
        ("sayang", "sayang"),
        ("sedap", "delicious"),
        ("sedikit sedikit lama lama jadi", "little by little can"),
        ("bukit", "accumulate to become"),
        ("senget", "slanted"),
        ("suka-suka", "like"),
        ("tak boleh tahan", "cannot withstand it"),
        ("tekan", "punish"),
        ("tikam", "game of chance"),
        ("tolong", "begs"),
        ("tompang", "to give a ride"),
        ("ulu", "isolated"),
        ("ah boh then?", "what else then?"),
            ("bak chew ba stamp", "blind"),
        ("pang chan", "give chance"),
        ("gan cheong", "very nervous"),
        ("pattern zhuay kuay badminton", "lots of excuses"),
        ("steady phon pi pi", "solid"),

        ("gao dim", "settled"),
        ("ko lo", "tall guy"),
        ("heng dai", "brother"),
        ("ham sup", "lecherous"),
        ("mong cha cha", "blur"),
        ("pak tor", "go on a date"),
        ("sam seng", "gangster"),
        ("siu dou", "crazy"),
        ("sup sup sui", "insignificant"),
        ("ta bao", "takeaway food"),
        ("yam seng", "cheers"),

        ("chio gao gay sha sha", "teeth-baring laugh"),
        ("ga li lor", "still early to say"),
        ("jiak bah buay?", "have you eaten?"),
        ("ya kuay lao ho sai", "very bored")
        ]

def paraphrase_singlish(string):
    for old,new in singlish_l:
        string = string.replace(old,new)
    return string




















